### ISSUE TITLE
brew formula not installing

### ISSUE THREAD

**Issue by amuino** [RipcordSoftware/AvanceDB#75]
I get the following error when trying to install from `brew` 

```
$ brew install ripcordsoftware/packages/avancedb
==> Installing avancedb from ripcordsoftware/packages
Error: ripcordsoftware/packages/avancedb contains conflicting version recursive dependencies:
  autoconf@2.13, autoconf
View these with `brew deps --tree ripcordsoftware/packages/avancedb`.
```

This is the dependency tree:
```
$ brew deps --tree ripcordsoftware/packages/avancedb
ripcordsoftware/packages/avancedb (required dependencies)
├── :git
├── wget
│   ├── pkg-config
│   └── openssl@1.1
├── autoconf@2.13
├── autoconf
├── automake
│   └── autoconf
├── libtool
```

And this is my `brew` environment (up-to-date as I write)
```
brew config
HOMEBREW_VERSION: 1.2.1
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: ea8be174f6009bc9bdec67b13ca501b5b83fc4b8
Last commit: 3 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 37954ce7325f848f5867b9e320a8e91895d7d619
Core tap last commit: 5 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.12.2 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/amuino/.rvm/rubies/ruby-2.2.4/bin/ruby
Java: 1.8.0_25, 1.6.0_65-b14-468
macOS: 10.12.5-x86_64
Xcode: 8.3.2
CLT: N/A
X11: 2.7.8 => /opt/X11
```

**Comment by timboldt** [comment]
Same here:

$ brew install ripcordsoftware/packages/avancedb
Updating Homebrew...
==> Installing avancedb from ripcordsoftware/packages
Error: ripcordsoftware/packages/avancedb contains conflicting version recursive dependencies:
  autoconf@2.13, autoconf
View these with `brew deps --tree ripcordsoftware/packages/avancedb`.

**Comment by craigminihan** [comment]
@amuino @timboldt This is odd. You can install both autoconf versions on the command line without any issue. 

There was a change to brew (https://github.com/Homebrew/brew/commit/e41f0bf8c8365c150935f03f3ecd14b44187b2ef) from a few months back which may have introduced the problem. I'll do more digging.

**Comment by craigminihan** [comment]
Raised with the brew team as https://github.com/Homebrew/brew/issues/2888

**Comment by craigminihan** [comment]
The brew team won't fix (looks like a nasty change so I'm going to update the formula and docs this end to make it work. Changed in d518af96c8c85f9169d53301481e45ee235cc577 and https://github.com/RipcordSoftware/homebrew-packages/commit/6060f411fb4882339973cbf2793d2c1631ae8fa8
